apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ledger-db-ca
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: demo-vault
  target:
    name: ledger-db-ca
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ca.crt
      remoteRef:
        key: multisite-ledger/replication
        property: ca_crt_b64
        decodingStrategy: Base64
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ledger-db-replication
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: demo-vault
  target:
    name: ledger-db-replication
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: multisite-ledger/replication
        property: tls_crt_b64
        decodingStrategy: Base64
    - secretKey: tls.key
      remoteRef:
        key: multisite-ledger/replication
        property: tls_key_b64
        decodingStrategy: Base64
