apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-web
spec:
  template:
    metadata:
      labels:
        demo.redhat.com/frontend-role: standby
    spec:
      containers:
        - name: web
          env:
            - name: WRITE_HOSTS
              value: ledger-postgres-site-a
            - name: WRITE_PORTS
              value: "5432"
            - name: LOCAL_READ_HOST
              value: ledger-db-replica-r
            - name: LOCAL_DB_LABEL
              value: Site B PostgreSQL streaming replica
