apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multisite-ledger
resources:
  - ../common
  - site-config.yaml
  - external-secret-replication.yaml
  - postgres-replica.yaml
  - service-interconnect.yaml
patches:
  - path: frontend-patch.yaml
