apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-web
spec:
  template:
    metadata:
      labels:
        demo.redhat.com/frontend-role: active
    spec:
      containers:
        - name: web
          env:
            - name: LOCAL_READ_HOST
              value: ledger-db-rw
            - name: LOCAL_DB_LABEL
              value: Site A PostgreSQL primary
