apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ledger-db-app
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: demo-vault
  target:
    name: ledger-db-app
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: multisite-ledger/app
        property: username
    - secretKey: password
      remoteRef:
        key: multisite-ledger/app
        property: password
    - secretKey: database
      remoteRef:
        key: multisite-ledger/app
        property: database
